name: Kernel Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  
  # Triggers the workflow thru GitHub API
  repository_dispatch:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:

      - name: Remove Work Dir
        run: rm -rf $GITHUB_WORKSPACE
        
      - name: Checkout Repo
        if: ${{ always() }}
        run: git clone git@github.com:PixelOS-Automated-Builds/ginkgo-kernel-workflow.git . 
          
      - name: Clone Kernel
        if: ${{ always() }}
        run: git clone git@github.com:geek0609/kernel_xiaomi_ginkgo.git --depth=1 -b 11.0 kernel 
          
      - name: Build
        if: ${{ always() }}
        run: cd kernel && bash build.sh
      
      - name: copy zip out
        if: ${{ always() }}
        run: cp kernel/*.zip . 
          
      - name: Post a Github Release
        run: hub release create -a *.zip -m 'Kernel Build' $(date +%s)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          
      - name: Remove Work Dir
        run: rm -rf $GITHUB_WORKSPACE
