# This is a basic workflow to help you get started with Actions

name: Kernel Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Install Deps
        if: ${{ always() }}
        run: |
          sudo apt-get install wget -y && sudo wget https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh && sudo bash android*
      # Runs a set of commands using the runners shell
      - name: Checkout Repo
        if: ${{ always() }}
        uses: actions/checkout@v2
          
      - name: Checkout Repo
        if: ${{ always() }}
        uses: actions/checkout@v2
        with:
          repository: ArrowOS-Devices/android_kernel_xiaomi_ginkgo
          path: kernel
          
      - name: Build
        if: ${{ always() }}
        run: cd kernel && sudo bash build.sh
        
      - name: Upload
        if: ${{ always() }}
        run: ls && cd kernel && curl --upload-file ./QuicksilveRV2-ginkgo*.zip http://transfer.sh/kernel.zip
      
      - name: copy zip out
        if: ${{ always() }}
        run: cp kernel/*.zip . 
        
      - name: remove kernel folder
        if: ${{ always() }}
        run: sudo rm -rf kernel
      
      - name: push
        if: ${{ always() }}
        run: |
          git config --global user.email "<>"
          git config --global user.name "Ashwin Kernel Builder [BOT]"
          git fetch
          git pull
          git add .
          git commit -m "Kernel Builder [BOT]"
          git push origin master
          
