name: Kernel Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  
  # Triggers the workflow thru GitHub API
  repository_dispatch:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      # Runs a set of commands using the runners shell
      - name: Checkout Repo
        if: ${{ always() }}
        uses: actions/checkout@v2
          
      - name: Checkout Repo
        if: ${{ always() }}
        uses: actions/checkout@v2
        with:
          repository: geek0609/kernel_xiaomi_ginkgo
          path: kernel
          fetch-depth: 1
          
      - name: Build
        if: ${{ always() }}
        run: cd kernel && bash build.sh
      
      - name: copy zip out
        if: ${{ always() }}
        run: cp kernel/*.zip . 
          
      - name: Post a Github Release
        run: hub release create -a *.zip -m 'Kernel Build' $(date +%s)
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEYS }}
