# This is a basic workflow to help you get started with Actions

name: Kernel Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Install Deps
        run: |
          sudo apt-get install wget -y && sudo wget https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh && sudo bash android*
      # Runs a set of commands using the runners shell
      - name: Sync Repo
        run: |
          sudo mkdir kernel && cd kernel && sudo git clone https://github.com/ghostrider-reborn/android_kernel_xiaomi_ginkgo --depth=1  .
          
      - name: Build
        run: |
          cd kernel && sudo bash build.sh
      - name: Upload
        run:  cd kernel && export URL = $(curl --upload-file ./QuicksilveRV2-ginkgo*.zip http://transfer.sh/kernel.zip)
      - name: Update through telegram
        run: CHAT = ${{ secrets.CHAT_ID }} && API = ${{ secrets.TELEGRAM_API }} && curl -s "https://api.telegram.org/bot${API}/sendmessage" --data "text=$URL&chat_id=${CHAT}"
          
